# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
fastlane_version "2.62.0"
default_platform(:ios)

platform :ios do

	desc "发布 测试版本 到 蒲公英"
  	lane :pgy do

	  	git_log = sh("git log --no-merges -1 --pretty=format:'# %ai%n# %B by %an'")

		automatic_code_signing(
			profile_uuid:"67ac2965-fa44-40e9-baf9-e1b4e8ed044a"
		)

	    gym(
	    	scheme: "Runner",
	    	export_method: "enterprise",
	    	output_directory: "output",
	    	configuration: "Release"
	    )

  		pgyer(
  			api_key: "01f1afe385c48954fd713ba5d533b62c",
  		 	user_key: "1355980667be03e4544e23214b5e8c14",
  		 	update_description: git_log
  		 )

	end

end


